# Generated by Django 4.1.1 on 2022-10-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('bg_id', models.IntegerField(db_column='BG_ID', primary_key=True, serialize=False)),
                ('blood_group', models.TextField(db_column='Blood_Group')),
            ],
            options={
                'db_table': 'Blood_Type',
                'managed': False,
            },
        ),
    ]
