# Generated by Django 4.1.1 on 2022-10-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployedList',
            fields=[
                ('deployed_id', models.AutoField(db_column='Deployed_ID', primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, db_column='Start_Date', null=True)),
                ('end_date', models.DateField(blank=True, db_column='End_Date', null=True)),
                ('no_of_days_served', models.IntegerField(blank=True, db_column='No_of_Days_Served', null=True)),
                ('actual_days', models.IntegerField(blank=True, db_column='Actual_Days', null=True)),
            ],
            options={
                'db_table': 'Deployed_List',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DesuupProfileDetail',
            fields=[
                ('name', models.TextField(db_column='Name')),
                ('did', models.CharField(db_column='DID', max_length=50)),
                ('cid', models.BigIntegerField(db_column='CID', primary_key=True, serialize=False)),
                ('dob', models.DateField(blank=True, db_column='DOB', null=True)),
                ('mobile_no', models.CharField(blank=True, db_column='Mobile_No', max_length=50, null=True)),
                ('email_id', models.CharField(blank=True, db_column='Email_ID', max_length=250, null=True)),
                ('profession', models.TextField(blank=True, db_column='Profession', null=True)),
                ('year_of_completion', models.CharField(blank=True, db_column='Year_of_Completion', max_length=50, null=True)),
                ('present_address', models.TextField(blank=True, db_column='Present_Address', null=True)),
                ('village', models.TextField(blank=True, db_column='Village', null=True)),
            ],
            options={
                'db_table': 'Desuup_Profile_Detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DzongkhagList',
            fields=[
                ('dzo_id', models.AutoField(db_column='Dzo_ID', primary_key=True, serialize=False)),
                ('dzongkhag', models.TextField(db_column='Dzongkhag')),
            ],
            options={
                'db_table': 'Dzongkhag_List',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('emp_id', models.IntegerField(db_column='Emp_ID', primary_key=True, serialize=False)),
                ('employment_status', models.TextField(db_column='Employment_Status')),
            ],
            options={
                'db_table': 'Employment_Status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('g_id', models.AutoField(db_column='G_ID', primary_key=True, serialize=False)),
                ('gender', models.TextField(db_column='Gender')),
            ],
            options={
                'db_table': 'Gender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GewogList',
            fields=[
                ('gewog_id', models.IntegerField(db_column='Gewog_ID', primary_key=True, serialize=False)),
                ('gewogs', models.TextField(db_column='Gewogs')),
            ],
            options={
                'db_table': 'Gewog_List',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marital',
            fields=[
                ('m_id', models.IntegerField(db_column='M_ID', primary_key=True, serialize=False)),
                ('marital', models.TextField(db_column='Marital')),
            ],
            options={
                'db_table': 'Marital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QualificationLevel',
            fields=[
                ('q_id', models.IntegerField(db_column='Q_ID', primary_key=True, serialize=False)),
                ('level', models.TextField(db_column='Level')),
            ],
            options={
                'db_table': 'Qualification_Level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('scheme_id', models.IntegerField(db_column='Scheme_ID', primary_key=True, serialize=False)),
                ('scheme', models.TextField(db_column='Scheme')),
            ],
            options={
                'db_table': 'Scheme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaterProjectDetail',
            fields=[
                ('project_id', models.AutoField(db_column='Project_ID', primary_key=True, serialize=False)),
                ('project_site', models.CharField(db_column='Project_Site', max_length=100)),
                ('tentative_launch_date', models.CharField(blank=True, db_column=' Tentative_Launch_Date', max_length=50, null=True)),
                ('launch_date', models.CharField(blank=True, db_column='Launch_Date', max_length=100, null=True)),
                ('progress', models.CharField(blank=True, db_column='Progress', max_length=50, null=True)),
                ('project_duration', models.CharField(blank=True, db_column='Project_Duration', max_length=50, null=True)),
                ('expected_date_of_completion', models.CharField(blank=True, db_column='Expected_Date_of_Completion', max_length=100, null=True)),
                ('date_of_completion', models.CharField(blank=True, db_column='Date_of_Completion', max_length=250, null=True)),
                ('beneficiaries_households_field', models.CharField(blank=True, db_column='Beneficiaries_Households ', max_length=50, null=True)),
                ('trenching_distance_field', models.CharField(blank=True, db_column='Trenching_Distance ', max_length=50, null=True)),
                ('distribution_distance_field', models.CharField(blank=True, db_column='Distribution_Distance ', max_length=50, null=True)),
                ('estd_budget_m_field', models.CharField(blank=True, db_column='Estd_Budget_(m)', max_length=50, null=True)),
                ('desuup_male_engaged', models.IntegerField(blank=True, db_column='Desuup_Male_Engaged', null=True)),
                ('desuup_female_engaged', models.IntegerField(blank=True, db_column='Desuup_Female_Engaged', null=True)),
                ('total_desuup', models.IntegerField(blank=True, db_column='Total_Desuup', null=True)),
                ('rba', models.IntegerField(blank=True, db_column='RBA', null=True)),
                ('civil', models.IntegerField(blank=True, db_column='Civil', null=True)),
                ('desuup_requirement', models.IntegerField(blank=True, db_column='Desuup_Requirement', null=True)),
                ('remarks', models.TextField(blank=True, db_column='Remarks', null=True)),
            ],
            options={
                'db_table': 'Water_Project_Detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaterProjectStatus',
            fields=[
                ('status_id', models.IntegerField(db_column='Status_ID', primary_key=True, serialize=False)),
                ('status', models.TextField(db_column='Status')),
            ],
            options={
                'db_table': 'Water_Project_Status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaterProjectWithdralList',
            fields=[
                ('withdral_id', models.AutoField(db_column='WIthdral_ID', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date')),
                ('remarks', models.TextField(blank=True, db_column='Remarks', null=True)),
            ],
            options={
                'db_table': 'Water_Project_Withdral_List',
                'managed': False,
            },
        ),
    ]
