# Generated by Django 4.1.1 on 2022-10-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nsapp', '0002_deployedlist_desuupprofiledetail_dzongkhaglist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('cid', models.BigIntegerField(db_column='CID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Desuup_Profile_Detail',
                'managed': False,
            },
        ),
    ]
